# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install poetry or other tools if needed
      - pip install --upgrade pip setuptools wheel
    post_install:
      # Install the package itself to make imports work
      - pip install -e .

# Python configuration
python:
  install:
    # Install documentation dependencies
    - requirements: docs/requirements.txt
    # Install the package
    - method: pip
      path: .
      extra_requirements:
        - docs

# Formats to build
formats:
  - pdf
  - epub
